---

- name: disable IPv6 forwarding
  lineinfile:
    path: /etc/sysctl.conf
    line: "{{item}}"
  with_items:
    - "net.ipv6.conf.all.disable_ipv6 = 1"
    - "net.ipv6.conf.default.disable_ipv6 = 1"
  tags:
    - disable_ipv6


- name: sysctl -p
  shell: sysctl -p
  tags:
    - sysctl_reload

- name: add epel key
  shell: rpm --import https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
  when: internet

- name: add epel
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  when: internet

# - name: yum update
#   yum: name=* state=latest
  
- name: disable iptables
  service: name=iptables state=stopped enabled=no
  when: ansible_distribution == 'CentOS'
  ignore_errors: true

- name: disable ip6tables
  service: name=ip6tables state=stopped enabled=no
  when: ansible_distribution == 'CentOS'
  ignore_errors: true

- name: disable firewalld
  service: name=firewalld state=stopped enabled=no
  when: ansible_distribution == 'CentOS'
  ignore_errors: true

- name: install prereq packages (epel-release,tar,xz,zip,unzip,curl,ipset)
  yum: name=epel-release,tar,xz,zip,unzip,curl,ipset,bzip2,lldpad state=present
  ignore_errors: true
  tags:
    - prereq_packages

- name: install utility packages (traceroute, wget, mlocate, net-tools,bind-utils)
  yum: name=traceroute,wget,mlocate,tcpdump,net-tools,bind-utils state=present
  ignore_errors: true

- name: install prereq Contiv packages (ansible,bzip2,python-netaddr,git,python-pip)
  yum: name=ansible,bzip2,python-netaddr,git,python-pip state=present
  tags:
    - contiv_prereq

- name: update SElinux
  shell: sudo sed -i s/SELINUX=enforcing/SELINUX=permissive/g /etc/selinux/config
  when: ansible_distribution == 'CentOS'

- name: setenforce 0
  shell: setenforce 0
  when: ansible_distribution == 'CentOS'

- name: enable passwordless sudo access
  #shell: echo '%wheel        ALL=(ALL)       NOPASSWD\: ALL' > /etc/sudoers
  lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL'"
  when: ansible_distribution == 'CentOS'


